### ISSUE TITLE
Missing `--max_prompt_length` argument running example_requests_client_alpaca_eval.py

### ISSUE THREAD

**Issue by milank94** [tenstorrent/tt-inference-server#51]
When running the [sample script from README](https://github.com/tenstorrent/tt-inference-server/tree/main/vllm-tt-metal-llama3-70b#run-example-clients-from-within-docker-container): `python example_requests_client_alpaca_eval.py --stream True --n_samples 805 --num_full_iterations 1 --batch_size 32` hitting the following error:

```bash
usage: example_requests_client_alpaca_eval.py [-h] [--stream STREAM] [--vllm_model VLLM_MODEL] [--n_samples N_SAMPLES] [--num_full_iterations NUM_FULL_ITERATIONS] [--batch_size BATCH_SIZE] [--input_seq_len INPUT_SEQ_LEN]
                                              [--output_seq_len OUTPUT_SEQ_LEN] [--tokenizer_model TOKENIZER_MODEL] [--dataset DATASET] --max_prompt_length MAX_PROMPT_LENGTH [--distribution {fixed,uniform,normal}] [--template TEMPLATE]
                                              [--save_path SAVE_PATH]
example_requests_client_alpaca_eval.py: error: the following arguments are required: --max_prompt_length
```

**Comment by milank94** [comment]
Tried to set a value, but then hit another error:

```bash
python example_requests_client_alpaca_eval.py --stream True --n_samples 805 --num_full_iterations 1 --batch_size 32 --max_prompt_length 2048
2024-12-02 06:29:50,867 - root - INFO - generate_prompts args=Namespace(batch_size=32, dataset='random', distribution='fixed', input_seq_len=-1, max_prompt_length=2048, n_samples=805, num_full_iterations=1, output_seq_len=2048, save_path=None, stream=True, template=None, tokenizer_model=None, vllm_model=True)
2024-12-02 06:29:50,867 - utils.prompt_generation - INFO - Generating random prompts...
Traceback (most recent call last):
  File "example_requests_client_alpaca_eval.py", line 253, in <module>
    prompts = generate_prompts(args)
  File "/home/user/app/utils/prompt_generation.py", line 267, in generate_prompts
    args.num_prompts,
AttributeError: 'Namespace' object has no attribute 'num_prompts'
```
