### ISSUE TITLE
vLLM+LLama3.1-70B docker container built from scratch caused an exception in load_model

### ISSUE THREAD

**Issue by yasuhiroitoTT** [tenstorrent/tt-inference-server#62]
When following initial setup steps from: https://github.com/tenstorrent/tt-inference-server/tree/main/vllm-tt-metal-llama3-70b#vllm-tt-metalium-llama-31-70b-inference-api + adding workaround for https://github.com/tenstorrent/tt-inference-server/issues/37, I got an exception like this during init phase of llama model. 

I think the exactly same docker file worked as expected until Dec/17/2024. 

This issue is easy to reproduce by deleting docker's build cache or using new hardware. 

```
Process SpawnProcess-1:                                                                                                                                                                          
Traceback (most recent call last):                                                                                                                                                               
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap                                                                                                                  
    self.run()                                                                                                                                                                                   
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run                                                                                                                         
    self._target(*self._args, **self._kwargs)                                                                                                                                                    
  File "/home/user/vllm/vllm/engine/multiprocessing/engine.py", line 391, in run_mp_engine                                                                                                       
    engine = MQLLMEngine.from_engine_args(engine_args=engine_args,                                                                                                                               
  File "/home/user/vllm/vllm/engine/multiprocessing/engine.py", line 139, in from_engine_args                                                                                                    
    return cls(                                                                                                                                                                                  
  File "/home/user/vllm/vllm/engine/multiprocessing/engine.py", line 78, in __init__                                                                                                             
    self.engine = LLMEngine(*args, **kwargs)                                                                                                                                                     
  File "/home/user/vllm/vllm/engine/llm_engine.py", line 335, in __init__                                                                                                                        
    self.model_executor = executor_class(                                                                                                                                                        
  File "/home/user/vllm/vllm/executor/executor_base.py", line 47, in __init__                                                                                                                    
    self._init_executor()                                                                                                                                                                        
  File "/home/user/vllm/vllm/executor/tt_executor.py", line 28, in _init_executor                                                                                                                
    self.driver_worker.load_model()                                                                                                                                                              
  File "/home/user/vllm/vllm/worker/tt_worker.py", line 225, in load_model                                                                                                                       
    self.model_runner.load_model()                                                                                                                                                               
  File "/home/user/vllm/vllm/worker/tt_model_runner.py", line 140, in load_model                                                                                                                 
    self.model = loader.load_model(model_config=self.model_config,                                                                                                                               
  File "/home/user/vllm/vllm/model_executor/model_loader/tt_loader.py", line 25, in load_model                                                                                                   
    model = model_class.initialize_vllm_model(model_config.hf_config, device_config.device, scheduler_config.max_num_seqs)                                                                       
AttributeError: type object 'TtLlamaModelForGeneration' has no attribute 'initialize_vllm_model'    
```

**Comment by tstescoTT** [comment]
I believe this issue was due to the change in tt-metal model implementation and vLLM integration in https://github.com/tenstorrent/tt-metal/commit/a16bdf4c346cd033e7a2652e6ab20cbf86df4a2e#diff-1ec45a3fba226bfd24ef790e1102c13f748007a6933e8dd07321e14066dde98f

@yasuhiroitoTT could you please verify if updating your local branch to current `main` (https://github.com/tenstorrent/tt-inference-server/tree/0bbdde04ce5e41b8bff479a23076097ab4f43aa2) resolves this issue for you?
